name: maaad

services:
  maaad:
    container_name: maaad
    build: .
    volumes:
      - ./config/:/aria2/config/
      - ./path-to-downloads/:/downloads/
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6880:6880
      - 6800:6800
    restart: on-failure
    logging:
      driver: json-file
      options:
        max-size: 1m
    networks:
      - default
